In [29]:
import pymysql
import pandas as pd

In [30]:
import os
from dotenv import load_dotenv, find_dotenv
dotenv_file = find_dotenv()
load_dotenv(dotenv_file)

True

In [55]:
conn = pymysql.connect(
    host=os.environ["a_host"],
    port = int(os.environ["a_port"]),
    database =os.environ["a_database"],
    user=os.environ["a_user"],
    password=os.environ["a_password"],
    charset=os.environ['charset']
)

In [40]:
df = pd.read_csv('final_book2.csv')

In [38]:
# tb_book 생성

mk_book_table = '''
CREATE TABLE IF NOT EXISTS tb_book (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR(500) NOT NULL,
full_title VARCHAR(500) NOT NULL,
author VARCHAR(500) NOT NULL,
translator VARCHAR(500) NULL,
etc_author VARCHAR(500) NULL,
author_list VARCHAR(500) NULL,
publish_date DATE NULL,
publisher VARCHAR(50) NULL,
introduction TEXT NULL,
isbn VARCHAR(20) NOT NULL,
page VARCHAR(10) NULL,
categories VARCHAR(500) NOT NULL,
url VARCHAR(100) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY unique_name (url)
)
'''

with conn.cursor() as cursor :
    cursor.execute(mk_book_table)
    conn.commit()

In [39]:
mk_USER1_table = '''
CREATE TABLE IF NOT EXISTS tb_user_books (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
book_id INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (book_id) REFERENCES tb_book(id)
)
'''

with conn.cursor() as cursor :
    cursor.execute(mk_USER1_table)
    conn.commit()

In [68]:
df.fillna('null', inplace=True)

In [69]:
df['isbn'] = df['isbn'].astype(str).str.replace('.', '')

In [43]:
df

,Unnamed: 0.1,Unnamed: 0,title,full_name,book_url,publisher,author_list,intro,category,date,pages,isbn,저자,역자,기타
0,0,37352,생성형 AI시대 산업별 기술혁신과 서비스사례 및 법적이슈 현안분석,생성형 AI시대 산업별 기술혁신과 서비스사례 및 법적이슈 현안분석 [ 양장 ],https://www.yes24.com/Product/Goods/124435593,지식산업정보원,"[['R&D정보센터', '244360']]",본원 R&D정보센터에서는 글로벌 거대 기업들의 약진이 거세지는 생성형 인공지능 시장...,1001025007004004,2025-04-01,630쪽,97889659602700,R&D정보센터저,null,null
1,1,5180,2024 대박 날 바이오 다크호스,2024 대박 날 바이오 다크호스,https://www.yes24.com/Product/Goods/123183541,이데일리,"[['팜이데일리 특별취재팀', '405108']]",『2024 대박 날 바이오 다크호스』와 함께미지의 길을 성공의 길로!『2024 대박...,1001025008005,2024-10-27,276쪽,97911981371590,팜이데일리 특별취재팀,null,null
2,2,21222,누구나 쉽게 배우는 실전 마케팅 전략,누구나 쉽게 배우는 실전 마케팅 전략 사례로 배우는 핵심 스킬,https://www.yes24.com/Product/Goods/133819969,다온길,"[['백미르', '424835']]",마케팅으로 세상을 바꾼다최고의 브랜드가 되는 법 : 마케팅 전략과 사례로 배우다마케...,"1001025009001, 1001025009004, 1001025011001",2024-10-25,224쪽,97911627510600,백미르,null,null
3,3,23639,도쿄 트렌드 인사이트 2025,도쿄 트렌드 인사이트 2025,https://www.yes24.com/Product/Goods/133966202,원앤원북스,"[['정희선', '232242']]","저성장, 인구 감소의 시대어떻게 소비자를 설득하고 새로운 시장을 만들 것인가 지난해...","1001025007004004, 1001025009005",2024-10-24,336쪽,97911856545460,정희선,null,null
4,4,35626,사례로 알아보는 돈 버는 부동산 경매,사례로 알아보는 돈 버는 부동산 경매 특수물건 경매 전문 변호사의 경매 비법,https://www.yes24.com/Product/Goods/133821086,새로운제안,"[['주희진', '443331']]",특수물건 부동산 경매를 통해 큰 수익을 올리고 싶은 독자들을 위해 다양한 성공사례와...,1001025010003,2024-10-21,320쪽,97889634626080,주희진,null,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56927,56927,46615,연봉 말고 5000만 원 더 벌기 + 2024 벤꾸리 가계부 다이어리,연봉 말고 5000만 원 더 벌기 + 2024 벤꾸리 가계부 다이어리 [ 전2권...,https://www.yes24.com/Product/Goods/123271846,시원북스,"[['강희연', '405528']]",이 상품은 YES24에서 구성한 상품입니다.(낱개 반품 불가).[도서] 연봉 말고 ...,1001025010004,null,600쪽,97889840548130,강희연,null,null
56928,56928,57628,"중국주식, 저평가된 강한 기업에 투자하라 + 지금 중국 주식 천만원이면 10년 후 ...","중국주식, 저평가된 강한 기업에 투자하라 + 지금 중국 주식 천만원이면 10년 후 ...",https://www.yes24.com/Product/Goods/15114743,YES24묶음상품-도서,"[['정순필'], ['정영재']]",* 지금 중국 주식 천만원이면 10년 후 강남 아파트를 산다\r\n\r\n지금 현재...,1001025010002,null,744쪽,97889584309710,"정순필,정영재",null,null
56929,56929,58852,직원이라면 어떻게 일해야 하는가,직원이라면 어떻게 일해야 하는가,https://www.yes24.com/Product/Goods/16025156,원앤원북스,[['김경준']],직장인을 위한 조직생활 교과서조직사회는 사회인이라면 누구나 한 번은 거쳐야 할 인생...,1001025001006,null,300쪽,97889509079690,김경준,null,null
56930,56930,61550,충전수업 세트,충전수업 세트 쩐의 흐름 + 부의 증식 [ 전2권 ],https://www.yes24.com/Product/Goods/59682596,아라크네,"[['양보석', '214044']]",이 상품은 YES24에서 구성한 상품입니다.(낱개 반품 불가).[도서] 충전수업 :...,1001025010004,null,쪽수확인중,97889439019050,양보석,null,null
56931,56931,63870,트렌드 코리아 2015 + 2015 한국을 뒤흔들 12가지 트렌드,트렌드 코리아 2015 + 2015 한국을 뒤흔들 12가지 트렌드,https://www.yes24.com/Product/Goods/15212300,YES24묶음상품-도서,"[['최지혜', '157166'], ['김서영', '146382'], ['전미영',...",* 트렌드 코리아 2015‘양의 해’ 소비트렌드 키워드는 COUNT SHEEP소비자...,1001025009005,null,858쪽,97889889582780,"최지혜,김서영,전미영,이향은,이준영,김난도",null,null

In [59]:
with conn.cursor() as cursor:
    cursor.execute("SHOW TABLES;") #SHOW TABLE STATUS : 자세히 보기
    tables = cursor.fetchall()

In [60]:
tables

(('sample_user',), ('tb_book',), ('tb_user_books',))

In [35]:
# # 테이블 삭제
# with conn.cursor() as cur:
#     cur.execute("DROP TABLE tb_book;")
#     conn.commit()

In [ ]:
try:
    conn = ()
    ...
    # 데이터 베이스 실행
except:
    ...
finally:
    conn.close()

In [47]:
require = ['title','full_name','저자', '역자', '기타', 'author_list','date','publisher','intro','isbn','pages', 'category', 'book_url' ]
insert_sql = """INSERT IGNORE INTO tb_book (title, full_title, author, translator, etc_author, author_list, publish_date, publisher, introduction, isbn, page, categories, url) VALUES 
(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

batch_size = 2000

try:
    with conn.cursor() as cursor:
        for start_idx in range(0, len(df), batch_size):
            batch_data = [tuple(df.loc[idx, require]) for idx in range(start_idx, min(start_idx + batch_size, len(df)))]
            
            cursor.executemany(insert_sql, batch_data)
            print(f"{start_idx + len(batch_data)}개 데이터 삽입 완료")
        
        conn.commit()

except Exception as e:
    print(f"에러 발생: {e}")

finally:
    conn.close()

2000개 데이터 삽입 완료
4000개 데이터 삽입 완료
6000개 데이터 삽입 완료
8000개 데이터 삽입 완료
10000개 데이터 삽입 완료
12000개 데이터 삽입 완료
14000개 데이터 삽입 완료
16000개 데이터 삽입 완료
18000개 데이터 삽입 완료
20000개 데이터 삽입 완료
22000개 데이터 삽입 완료
24000개 데이터 삽입 완료
26000개 데이터 삽입 완료
28000개 데이터 삽입 완료
30000개 데이터 삽입 완료
32000개 데이터 삽입 완료
34000개 데이터 삽입 완료
36000개 데이터 삽입 완료
38000개 데이터 삽입 완료
40000개 데이터 삽입 완료
42000개 데이터 삽입 완료
44000개 데이터 삽입 완료
46000개 데이터 삽입 완료
48000개 데이터 삽입 완료
50000개 데이터 삽입 완료
52000개 데이터 삽입 완료
54000개 데이터 삽입 완료
56000개 데이터 삽입 완료
56932개 데이터 삽입 완료

In [27]:
# exectuemany 한 번에
# require = ['title', 'full_name', '저자', '역자', '기타', 'author_list', 'date', 'publisher', 'intro', 'isbn', 'pages', 'category', 'book_url']
# insert_sql = """INSERT IGNORE INTO tb_book (title, full_title, author, translator, etc_author, author_list, publish_date, publisher, introduction, isbn, page, categories, url) VALUES 
# (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

# try:
#     with conn.cursor() as cursor:
#         # 데이터 리스트 생성
#         data_list = [tuple(df.loc[idx, require]) for idx in range(len(df))]

#         # executemany로 한번에 삽입
#         cursor.executemany(insert_sql, data_list)

#         print("데이터 삽입 완료")
#         conn.commit()
# except Exception as e:
#     print(f"에러 발생: {e}")
# finally:
#     conn.close()

In [46]:
# # 강사님 가이드
# with conn.cursor() as cursor:
#     # 길이를 2000개씩 나누기
#     df.iloc[] # 인덱스 값 넣기 2000개씩 가져올 수 있게
#     cursor.executemany(SQL, [(), ()]) # 에러 처리
# conn.commit()

# sample_user 생성

In [53]:
df = pd.read_csv('final_book2.csv')[50:57]
df.fillna('null', inplace=True)
df['isbn'] = df['isbn'].astype(str).str.replace('.', '')
df = df.reset_index(drop=True)

In [52]:
# sample_user 생성

mk_sample_user_table = '''
CREATE TABLE IF NOT EXISTS sample_user (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR(500) NOT NULL,
full_title VARCHAR(500) NOT NULL,
author VARCHAR(500) NOT NULL,
translator VARCHAR(500) NULL,
etc_author VARCHAR(500) NULL,
author_list VARCHAR(500) NULL,
publish_date DATE NULL,
publisher VARCHAR(50) NULL,
introduction TEXT NULL,
isbn VARCHAR(20) NOT NULL,
page VARCHAR(10) NULL,
categories VARCHAR(500) NOT NULL,
url VARCHAR(100) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY unique_name (url)
)
'''

with conn.cursor() as cursor :
    cursor.execute(mk_sample_user_table)
    conn.commit()

In [70]:
require = ['title','full_name','저자', '역자', '기타', 'author_list','date','publisher','intro','isbn','pages', 'category', 'book_url' ]
insert_data = """INSERT IGNORE INTO sample_user (title, full_title, author, translator, etc_author, author_list, publish_date, publisher, introduction, isbn, page, categories, url) VALUES 
(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"""

with conn.cursor() as cursor:
    for idx in range(len(df)):
        print(tuple(df.loc[idx, require]))
        cursor.execute(insert_data, tuple(df.loc[idx, require]))
    conn.commit()

('마르크스 자본론', '마르크스 자본론 자본주의와 부의 메커니즘이 한눈에 밝혀진다!  ', '서희경', '시라이 사토시 감수', 'null', "[['서희경', '254986'], ['시라이 사토시', '206618']]", '2024-09-30', '소보랩', '현대인이 꼭 알아야 할 경제학 클래식우리가 지금, 『마르크스 자본론』을 읽어야 하는 이유‘일에서 보람을 느끼지 못한다’ ‘매일 회사에 가는 것이 우울하다’ 많은 직장인이 노동의 가치와 의미를 느끼지 못하는 이유는 단순한 개인적 문제가 아니라 자본주의 체제의 구조적 문제에서 비롯된 것이다. 자본주의 사회에서는 노동이 상품화된다. 노동자는 노동력 외에 팔 수 있는 상품이 없고, 자신의 노동으로 산출한 생산물에 대한 소유권을 가지지 못한다. 이러한 구조는 노동자가 자신의 일에 자율성을 갖지 못하게 하며, 단순히 임금을 받기 위해 일하는 존재로 전락하게 만든다. 이로 인해 일에서 자부심과 성취감을 느끼기 어렵게 된 것이다. 자본주의는 효율성과 생산성만을 강조하며 노동자들 간의 경쟁을 심화시키고, 개인의 고립을 초래한다. 경쟁이 치열해지면 협력과 상호작용이 방해받고, 노동자들은 서로를 동료가 아닌 경쟁자로 인식하게 된다. 이러한 경쟁 환경은 노동자들에게 고립감과 소외감을 느끼게 하고, 자신의 삶에 대한 회의감과 무력감으로 이어질 수 있다. 또한, 과잉소비를 유도하여 노동자들이 지속적으로 경제적 압박을 받게 만든다. 마르크스는 자본이 소비를 자극하고, 이를 통해 추가적인 이윤을 창출한다고 설명했다. 현대 사회에서는 광고와 마케팅이 소비를 자극하고, 소비자들이 계속해서 새로운 제품을 구매하도록 유도한다. 이로 인해 노동자들은 필요에 의해서가 아니라, 자본주의 시스템이 조작한 욕구에 의해 소비하게 되며, 이는 경제적 부담을 가중한다.마르크스는 노동자들이 자신의 노동에 대한 통제권을 회복하고, 인간적인 가치를 존중받을 수 있는 사회를 꿈꾸었다. 그의 경제학적 통찰은 현대 자본주의 사회에서 노동자들이 직면하는 문제를 이해하는 데 중요한 시사점을 제공한다. 자본주의의 문제점을 인식하고, 이를 해결하기 위한 방안을 모색함으로써 노동자가 자신의 삶에서 자부심과 성취감을 느끼고, 인간적인 가치를 존중받을 수 있는 사회를 구축하는 것이 중요하다. 『마르크스 자본론』을 통해 우리는 자본주의의 본질과 문제점을 명확히 인식하고 자유와 노동의 균형을 바로잡을 수 있는 통찰을 배우게 될 것이다.', '97720058250010', '192쪽', '1001025007003', 'https://www.yes24.com/Product/Goods/132739165')
('피벗의 시대 2025년 경제전망', '피벗의 시대 2025년 경제전망 2025년을 결정지을 18대 경제트렌드  ', '김광석', 'null', 'null', "[['김광석', '196660']]", '2024-09-30', '이든하우스', "금리 인하 이후 세계 경제와 한국 경제는 어떻게 변화할까? 미국 경기침체와 세계 경제 불황에 대한 우려, 이는 과연 과도한 공포일까? 2024년 8월 5일, 엔 캐리 청산으로 세계 주식시장이 급락했다. 미국 경제 침체에 대한 우려가 커졌지만, 다음 날 긍정적인 경제지표가 발표되면서 시장은 진정되었다. 그러나 '미국 경제 침체'에 대한 불안은 여전히 깊이 남아 있다. 2025년은 세계 경제가 구조적으로 변화하는 전환점이다. 팬데믹, 러시아-우크라이나 전쟁, 초인플레이션, 고금리 등의 충격으로 세계 경제는 혼란을 겪었으며, 그 여파로 저성장이 고착화될 가능성이 크다. 이 책은 2025년을 ‘항복점’으로 정의하고, 세계와 한국 경제의 변화를 예측하며, 이에 대한 대응 전략을 제시한다. 피벗(Pivot)은 금리 인하와 통화정책의 변화를 의미하며, 이 책은 이러한 전환의 시대에 어떻게 대비할지 논의한다.", '97889867132200', '310쪽', '1001025007004004, 1001025009005', 'https://www.yes24.com/Product/Goods/133233432')
('홍대리, 원온원 미팅을 시작하다', '홍대리, 원온원 미팅을 시작하다  ', '손창훈,유하림', 'null', 'null', "[['손창훈', '427377'], ['유하림', '470829']]", '2024-09-30', '가인지북스', "대한민국 청년들과 사회초년생 직장인들이 즐겁고 행복한 직장생활을 영위하기 위해 꼭 알아야 할 '원온원(1on1)'의 중요성을 다룬 책이다. 이 책은 리더와 팔로워의 시대를 넘어, 동료 간의 협력을 중시하는 새로운 조직문화를 제안한다. 상명하복의 전통적 조직문화를 넘어서, 협력 중심의 문화로 나아가는 방법을 제시하며, 대한민국 모든 직장인과 청년들이 더욱 즐겁고 보람 있는 일터를 만들 수 있도록 돕는다. 소통의 중요성, 원온원의 필요성, 그리고 상호 간의 시행착오를 줄이는 구체적인 방법을 소개한다. 성장을 꿈꾸는 모든 직장인들을 위한 필독서로 자리매김하기를 바라며, 이 책이 모든 직장인들이 일을 시작하기 전에 반드시 읽어야 할 '필필필' 필독서가 되기를 희망한다.", '97889763303520', '250쪽', '1001025008007', 'https://www.yes24.com/Product/Goods/133810169')
('박태웅의 AI 강의 2025', '박태웅의 AI 강의 2025 인공지능의 출현부터 일상으로의 침투까지 우리와 미래를 함께할 새로운 지능의 모든 것   [ 초판한정 : 2025 캘린더 브로마이드 (책과랩핑) ]', '박태웅', 'null', 'null', "[['박태웅', '352594']]", '2024-09-30', '한빛비즈', '독자들이 꼽은 인공지능 분야 최고의 책베스트셀러 『박태웅의 AI 강의』, 최신 AI 트렌드를 담아 돌아오다!2022년 11월 30일 오픈AI의 챗GPT가 등장한 이후, 이듬해 2023년은 ‘AI 쇼크’의 해라고 불러도 될 정도로 인공지능에 대한 관심이 폭발적이었다. 인간처럼, 아니 인간보다 더 글을 잘 써대는 이 생성형 AI를 두고 충격과 놀라움이 2023년 초부터 쏟아졌다. 그리고 이내 서점은 온통 GPT 관련 책으로 도배가 되다시피 했다. 챗GPT의 정체를 설명한 책부터 심지어 챗GPT와 공저한 책까지 등장한 것이다. 하루가 멀다 하고 쏟아지는 인공지능 도서의 홍수 속에서 독자들로부터 압도적으로 선택받은 책이 있었으니, 바로 ‘IT 현자’로 불리는 『박태웅의 AI 강의』였다. 딥러닝, 매개변수, 토큰, 트랜스포머, 강화학습 등등 인공지능을 알기 위해서는 필수적이지만 일반인에게는 낯설고 어렵게 느껴지는 개념들을 저자 특유의 편한 글투로 쉽게 설명하여 누구라도 AI 리터러시를 갖출 수 있게 도운 것이다. 심지어 청소년들도 이해할 수 있도록 풀어 쓴 수준이라 2023년 청소년 교양도서 우수도서로 선정되었고, 올해는 독자들이 뽑은 인공지능 분야 최고의 책으로도 선택되었다.바로 그 책이 최신 AI 트렌드와 더 깊은 인사이트를 담아 『박태웅의 AI 강의 2025』로 돌아왔다. 인공지능 원리에 대한 쉬운 설명은 그대로 유지한 채 더욱 깊이 있는 기술 지식이 책 곳곳에 추가되었고, 우리가 반드시 알아야 할 AI 트렌드는 물론이요, AI로 인해 변화될 앞으로의 우리 모습까지 조망하고 있다. 또한 AI 업계를 이끌고 있는 슈퍼 엘리트들의 사상적 배경을 소개하여 인공지능에 대해 심도 있는 이해를 돕고 있으며, 인공지능 윤리와 위험성, 그리고 관련 규제를 아우르는 사회적 인사이트까지 제시한다. 그로 인해 이번 책은 두 배 이상 두꺼워졌다. 한마디로 더 넓어지고 더 깊어진 것이다. 인공지능에 대해 ‘쉬우면서도 깊이 있는 지식’을 원한다면, 『박태웅의 AI 강의 2025』를 선택할 수밖에 없을 거라 단언한다.', '97911860390520', '420쪽', '1001025007004004', 'https://www.yes24.com/Product/Goods/133308510')
('부동산 트렌드 2025', '부동산 트렌드 2025 하버드 박사 김경민 교수의 부동산  투자 리포트  ', '김경민,김규석,이소영,이보람,이영민,정재훈', 'null', 'null', "[['김경민', '157788'], ['김규석', '420944'], ['이소영', '470365'], ['이보람', '470366'], ['이영민', '470367'], ['정재훈', '470368']]", '2024-09-30', '와이즈맵', '2025년 서울 부동산, 슈퍼사이클에 돌입하다매년 빅데이터 분석을 근거로 서울시 집값 예상치와 당해의 투자 이슈를 짚어주는 ≪부동산 트렌드≫ 시리즈가 2025년 부동산 시장을 전격 해부한다. 2024년 현재, 각종 매체에는 상승장이 왔으니 ‘영끌’해서라도 집을 마련해야 한다는 의견과, 부동산 시장이 붕괴될 것이니 있는 집도 팔라는 의견이 뒤섞여 있다. 상반된 주장에 혼란스러운 투자자들은 정확한 데이터와 균형 있는 의견을 제시해줄 전문가를 절실히 찾고 있다. 이에 김경민 서울대 교수는 “서울 부동산은 2021년도의 전 고점을 넘어 신고가를 기록할 것”이라며 확실한 ‘상승’ 방향을 예고한다. 역대 최악의 공급 부족과 금리 인하 신호, PF 문제 연장, 전셋값 폭등 등 시장의 모든 지표가 가격을 밀어 올릴 준비를 갖췄기 때문이다. 심지어 강남 부동산은 이미 슈퍼사이클 진입을 완료했다. 『부동산 트렌드 2025』는 더욱 정밀해진 분석으로 ‘2025년 집값 시나리오’를 제시한다. 투자자들은 이 책의 전망을 통해 상승의 시기와 폭을 정확히 인지하고, 자신의 상황에 맞는 부동산 전략을 세울 수 있을 것이다.', '97889503058020', '320쪽', '1001025010003', 'https://www.yes24.com/Product/Goods/133322963')
('오픈', '오픈 비즈니스 패권의 열쇠  ', '박수홍', 'null', 'null', "[['박수홍', '471272']]", '2024-09-30', '한빛미디어', '“오픈소스는 순수하지 않다”공유와 협업의 가치 뒤에 숨은 ‘오픈’의 본질리눅스 재단 최고운영진이 들려주는 오픈의 시대를 항해하는 지침서오픈, 공유와 협력이라는 선의 뒤에 숨은 속내를 분명히 알아야 한다. 오픈소스는 순수한 동기처럼 보이지만 순수하지 않은 이유를 여러 사례를 통해 ‘오픈’이 주는 효용과 해악을 알려주고, 그 가운데 우리가 오픈을 해야 하는 이유를 스스로 깨닫게 한다. 성공한 오픈의 조건과 글로벌 빅테크가 선택한 오픈은 어떤 결과로 이어지고 있는지, 오픈의 세계를 살아가는 우리가 오픈을 어떤 방향으로 이끌어야 하는지 기꺼이 가이드 역할을 자청한다. 비즈니스 암투 속에서 살아남기 위해, 오픈이라는 광야에서 길을 잃지 않기 위해 지금 바로 책의 첫 장을 오픈하라.', '97889597519760', '232쪽', '1001025008006, 1001025009005', 'https://www.yes24.com/Product/Goods/133872990')
('한국경제사', '한국경제사   [ 양장 ]', '안병직,조영준,박이택,주익종', 'null', 'null', "[['안병직', '151040'], ['조영준', '257368'], ['박이택', '471458'], ['주익종', '118318']]", '2024-09-30', '율곡출판사', '한국경제사는 다양한 시각을 가지고 관찰될 수 있을 것이나, 이 책은 위에서 보는 바와 같이, 세계 자본주의 발달의 제3유형이라는 시각을 가지고 한국 경제의 발전과정을 살펴본 것이다. 이러한 역사적 서술을 위해서는 세계 자본주의 발달의 제3유형에 관한 자세한 이론적 정리가 선행해야 하겠으나, 그렇게 하지 못했다. 다만 세계 자본주의의 유형적 발달에 관한 거친 틀만을 가지고 한국경제사의 발달과정을 개략적으로 살펴본 것이다. 그리고 이 책의 집필에 있어서는 필자가 그 개략적인 틀을 짜고 각 장의 서술방향을 제시하기는 했으나, 능력 부족으로 필자가 직접 집필하지는 못하고 여러 연구자들에게 집필을 의뢰하지 않을 수 없었다. 제1편의 제1·2장은 안병직이, 그리고 제3~5장은 조영준이, 제2편은 박이택이, 제3편은 주익종이 각각 집필했다. 이 책은 한국경제사에 대한 창의적 해석보다는 명확한 방향 제시를 목표로 했다.', '97889831708970', '534쪽', '1001025007004003', 'https://www.yes24.com/Product/Goods/133969252')